flowchart LR
  OS[Onchain Sequencer]

  O[Ordering Module]
  I[Inclusion Module]
  E[Economic Module]
  G[Governance Module]
  A[Atomicity Module]

  OS --> O
  OS --> I
  OS --> E
  OS --> G
  OS --> A
